---
AWSTemplateFormatVersion: 2010-09-09
Description: Lambda function for AI assistant use case interacting with Bedrock Knowledge Base
Parameters:
  BedrockKnowledgeBaseId:
    Type: String
    Description: Bedrock Knowledge Base Id
  BedrockLambdaFunctionName:
    Type: String
    Description: Name of the Lambda function interacting with Bedrock
    Default: webapp-lambda-knowledgebase-bedrock
  BedrockLambdaFunctionMemorySize:
    Type: Number
    Description: Memory size of the Lambda function interacting with Bedrock
    Default: 1024
  BedrockLambdaFunctionRuntime:
    Type: String
    Description: Runtime of the Lambda function interacting with Bedrock
    Default: python3.12
  BedrockLambdaS3Bucket:
    Type: String
    Description: S3 bucket for the Lambda function's code (zip file)
  BedrockLambdaS3Key:
    Type: String
    Description: S3 key for the Lambda function's code (zip file)
  BedrockModelName:
    Type: String
    Description: Bedrock Model Name
    Default: anthropic.claude-instant-v1

Resources:
  ################### Lambda function resources to interact with Bedrock Knowledgebase #################
  BedrockLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function interacting with Bedrock Knowledge base
      FunctionName: !Ref BedrockLambdaFunctionName
      Runtime: !Ref BedrockLambdaFunctionRuntime
      Handler: index.handler
      Role: !GetAtt BedrockLambdaFunctionRole.Arn
      MemorySize: !Ref BedrockLambdaFunctionMemorySize
      Environment:
        Variables:
          KnowledgeBaseId: !Ref BedrockKnowledgeBaseId
          BedrockModelName: !Ref BedrockModelName
      Timeout: 60
      Code:
        S3Bucket: !Ref BedrockLambdaS3Bucket
        S3Key: !Ref BedrockLambdaS3Key

  BedrockLambdaFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BedrockLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  BedrockLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaFunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - bedrock:InvokeModel
                  - bedrock:Retrieve
                  - bedrock:RetrieveAndGenerate
                Resource: "*"

Outputs:
  BedrockLambdaFunctionName:
    Description: Bedrock Lambda Function Name
    Value: !Ref BedrockLambdaFunctionName
    Export:
      Name: !Sub "${AWS::StackName}-BedrockLambdaFunctionNameExportName"
  BedrockLambdaFunctionArn:
    Description: Bedrock Lambda Function Arn
    Value: !GetAtt BedrockLambdaFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BedrockLambdaFunctionArnExportName"